version: '3.7'
services:
  postgres:
    image: postgres:10.12
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
  mongodb_container:
    image: mongo:4.4
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  postgresdata:
  mongodb_data_container: