version: '3.7'
services:
  postgres:
    image: postgres:10.12
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
volumes:
  postgresdata: