version: '3.7'
services:
  postgres:
    image: postgres:10.12
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
volumes:
  postgresdata: